import { motion } from 'framer-motion'
import { useEffect, useState } from 'react'
import { fetchNarrative } from '../lib/api'
import type { Narrative } from '../lib/types'

interface NarrativeCardProps {
  transactionId: string
  showBriefing?: boolean
}

export default function NarrativeCard({ transactionId, showBriefing = false }: NarrativeCardProps) {
  const [narrative, setNarrative] = useState<Narrative | null>(null)
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState(false)

  useEffect(() => {
    let cancelled = false
    setLoading(true)
    setError(false)
    fetchNarrative(transactionId)
      .then((n) => {
        if (!cancelled) setNarrative(n)
      })
      .catch(() => {
        if (!cancelled) setError(true)
      })
      .finally(() => {
        if (!cancelled) setLoading(false)
      })
    return () => {
      cancelled = true
    }
  }, [transactionId])

  if (loading) {
    return (
      <div className="narrative-card narrative-loading">
        <span className="spinner" /> Generating narrative…
      </div>
    )
  }

  if (error || !narrative) {
    return <div className="narrative-card narrative-error">Couldn't generate a narrative for this transaction.</div>
  }

  return (
    <motion.div
      className="narrative-card"
      initial={{ opacity: 0, y: 6 }}
      animate={{ opacity: 1, y: 0 }}
      transition={{ duration: 0.3 }}
    >
      <div className="narrative-badge-row">
        <span className={`narrative-provider-badge ${narrative.provider}`}>
          {narrative.provider === 'real' ? 'Generated by Claude' : 'Simulated narrative'}
        </span>
      </div>

      <div className="narrative-block">
        <span className="narrative-label">Customer message</span>
        <p>{narrative.customer_message}</p>
      </div>

      <div className="narrative-block">
        <span className="narrative-label">Plain-English explanation</span>
        <p>{narrative.audit_explanation}</p>
      </div>

      {showBriefing && narrative.escalation_briefing && (
        <div className="narrative-block narrative-briefing">
          <span className="narrative-label">Briefing for the human agent</span>
          <p>{narrative.escalation_briefing}</p>
        </div>
      )}
    </motion.div>
  )
}
